### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by CesarCoelho** [talent518/ftp-gui#1]
Hi,

This project looks very interesting! Can you add a License to the project?
My preference is MIT License as it is well known in the industry.

Best regards,
César Coelho

**Comment by talent518** [comment]
Thank you for your support. I have added the license file to the project.
My English is not good, this Baidu online translation, please understand.

**Comment by talent518** [comment]
> Hi,
> 
> This project looks very interesting! Can you add a License to the project?
> My preference is MIT License as it is well known in the industry.
> 
> Best regards,
> César Coelho

Thank you for your support. I have added the license file to the project.
My English is not good, this Baidu online translation, please understand.

**Comment by CesarCoelho** [comment]
Thank you very much!
